### ISSUE TITLE
Assembly Info Reader Doesn't Successfully Read Info - v1.2.2 (worked in v1.1.0)

### ISSUE THREAD

**Issue by smaglio81** [kyleherzog/AssemblyInfoReaderTask#13]
## Issue

The Assembly Info Reader Task (v1.2.2) no longer reads our "partial" AssemblyVersionInfo.cs file.

The is what the build output from Azure Dev Ops looks like this morning (it is missing all the `Setting variable XXXXXX to YYYYY` lines):

![image](https://user-images.githubusercontent.com/169953/64481790-be553480-d198-11e9-9a5d-3c210d13b1e9.png)

## Expected

The same build/task/step was working yesterday with v1.1.0.

![image](https://user-images.githubusercontent.com/169953/64481794-daf16c80-d198-11e9-8482-14e24f5ba966.png)

Here is the contents of the "partial" AssemblyVersionInfo.cs file that we use

```
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]

```

And, here is the configuration of the task through the web interface:

![image](https://user-images.githubusercontent.com/169953/64481822-71259280-d199-11e9-9f8e-038cfb6943bf.png)

## Troubleshooting

The audit logs in Azure Dev Ops makes it look like the new version was installed this morning. I'm not sure how to get the old version back.

![image](https://user-images.githubusercontent.com/169953/64481804-04aa9380-d199-11e9-9a8f-f57ecdcffd6d.png)

**Comment by kyleherzog** [comment]
Can you change your search "Path to AssemblyInfo file" to end in .cs?

**Comment by kyleherzog** [comment]
Actually, I just pushed out v1.2.3. This version should fix the issue without you needing to change anything on your end.  Can you confirm that it fixes your issue?

**Comment by smaglio81** [comment]
Thank You! The update to v1.2.3 fixed this.

Thanks again for the quick turnaround!

(I was nervous that I was gonna have to tell our developers (about 40 people) that their builds were going to be broken tomorrow morning.)
