### ISSUE TITLE
'AssembyInfoReader' (1.2.3) is using deprecated task execution handler. 

### ISSUE THREAD

**Issue by gautamksr** [kyleherzog/AssemblyInfoReaderTask#15]
Getting the warning message in ADO CI
##[warning]Task 'AssembyInfoReader' (1.2.3) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by bkwdesign** [comment]
While this task works perfectly for me in Azure DevOps Build pipeline, it does also generate this warning for me.  

Thank you for creating this tool.

**Comment by kyleherzog** [comment]
Version 2 of the task has now been released to address this issue.  Please update your build definitions to use the new version of the task.
