### ISSUE TITLE
Does not parse strings with literal operator

### ISSUE THREAD

**Issue by dtorg** [kyleherzog/AssemblyInfoReaderTask#2]
In some cases, the AssemblyVersion may have a literal operator "@" symbol. In this case, the tool wont process the string. Example [assembly: AssemblyVersion(@"1.1.0.0")]. Is there a workaround?

**Comment by kyleherzog** [comment]
I haven't testing this fix out yet, but if you can find the file AssemblyInfoReaderTask.ps1 on your build/release server,  I'm thinking you could just swap out this line:

$matches = [regex]::Matches($content, '(?m)^\s*\[\s*assembly:\s*(\w*)\(\s*"([^"]*)')

with this one:

$matches = [regex]::Matches($content, '(?m)^\s*\[\s*assembly:\s*(\w*)\(\s*@?"([^"]*)')

The other option would be to remove the literal operator from the source file if possible.

**Comment by dtorg** [comment]
I am not familiar how these are installed. Where would I look?

Thanks,
David R. Torgerson | Director Software Applications | Direct.: (512) 381-3233 | dtorg@luminexcorp.com<mailto:dtorg@luminexcorp.com>
Luminex Corporation | 12212 Technology Blvd, Austin, TX  78727 | www.luminexcorp.com<http://www.luminexcorp.com/>

**Comment by kyleherzog** [comment]
Actually, if you look in your build log and search for "AssemblyInfoReader.ps1", you should find a line that says "Executing the powershell script: ...\AssemblyInfoReader.ps1"  That line should give you the full path to the file on your machine with the build agent on it.

**Comment by kyleherzog** [comment]
The string literal operator support has been added with version 1.1.
