### ISSUE TITLE
Error: [System.Text.RegularExpressions.Group] does not contain a method named 'Replace'.

### ISSUE THREAD

**Issue by cepino** [kyleherzog/AssemblyInfoReaderTask#22]
Version      : 3.0.0
...
...

Using CSharp/VbNet regex expression (?m)^\s*[\[\<]\s*[Aa]ssembly:\s*([\w\.]*)\(\s*@?"([^"]*)
##[error]Method invocation failed because [System.Text.RegularExpressions.Group] does not contain a method named 'Replace'.

**Comment by MscrmTools** [comment]
Same here

**Comment by kyleherzog** [comment]
Thanks for the feedback.  Just released v3.0.1 to address this issue.  Please give that a try.

**Comment by cepino** [comment]
Version 3.0.1 resolves the issue. Thank you.
