### ISSUE TITLE
Version 1.1.0 generates a deprecation warning

### ISSUE THREAD

**Issue by maartenkools** [kyleherzog/AssemblyInfoReaderTask#7]
The latest version of the task generates a deprecation warning:

> ##[warning]Task 'AssembyInfoReader' (1.1.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by kyleherzog** [comment]
Looks like the execution type of the task needs to be upgraded from Powershell to Powershell3.

**Comment by kyleherzog** [comment]
I was hoping this was just a manifest change but is requires a rework of the powershell script as well.  Documentation of the PowerShell3 SDK is here: https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/README.md  

Placing this on hold for now.

**Comment by gautamksr** [comment]
I am facing the same issues. not able to get the $(AssemblyInfo.AssemblyVersion.Major) variable value.

##[warning]Task 'AssembyInfoReader' (1.2.3) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by kyleherzog** [comment]
Version 2 of the task has now been released to address this issue.  Please update your build definitions to use the new version of the task.
